services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: nse
      POSTGRES_USER: sniper
      POSTGRES_PASSWORD: nG5y$w2!qR8j@x1L^M7dV6*ZbP9#t4K
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=P8r#1tX9&zL7wF^2jK5yG@3vQ6mZ!
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=postgres://sniper:nG5y$w2!qR8j@x1L^M7dV6*ZbP9#t4K@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
